[package]
name = "wmjtyd-libstock"
description = "The utilities for operating stocks"
authors = ["pan93412"]
version = "0.1.0"
edition = "2021"
readme = "./README.md"
license = "Apache-2.0"
keywords = ["stock", "utility", "wmjtyd"]
repository = "https://github.com/wmjtyd/libstock"
documentation = "https://docs.rs/wmjtyd-libstock"
homepage = "https://github.com/wmjtyd/libstock"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.2"
chrono = "0.4.19"
concat-string = "1.0.1"
crypto-crawler = { version = "4.4.5", optional = true }
crypto-msg-parser = { version = "2.5.4", optional = true }
either = "1.6.1"
flume = "0.10.13"
once_cell = "1.12.0"
rust_decimal = "1.25.0"
thiserror = "1.0.31"
tokio = { version = "1.19.2", features = ["rt", "fs", "io-util"] }
tracing = "0.1.35"

[features]
default = ["crypto"]
crypto = ["dep:crypto-msg-parser", "dep:crypto-crawler"]
