name: Test documenting libstock

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          feature="$(python3 scripts/list_all_possible_features.py)"
          echo "::set-output name=feature::$feature"
    outputs:
      feature: ${{ steps.set-matrix.outputs.feature }}

  doccheck:
    needs: build-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        features: ${{ fromJson(needs.build-matrix.outputs.feature) }}

    steps:
      - uses: actions/checkout@v3
      - name: Trying to generate docs
        run: |
          for f in ${{ matrix.features }}; do
            echo -e "\ninfo: doccheck with $f"
            cargo doc --no-deps --no-default-features -F "$f"
          done
        env:
          RUSTDOCFLAGS: "-Dwarnings"
